#!/bin/bash -x
PROFILE="$1"
IFILE="$2"
OFILE="$3"
LIBDIR=/home/martin/video
. "$LIBDIR/$PROFILE"

die() {
    echo >&2 "$@"
    exit 1
}
case $CONTAINER in
    ogg)
	OPTS="$OPTS -f ogg"
	;;
esac
case $VCODEC-$ACODEC in
    s263-samr)
	OPTS="$OPTS -s qcif -acodec libamr_nb -ar 8000 -ac 1 -ab 7950"
	;;
    *)
	# special cases out of the way, now handle a-v separately
	if [ -z "$VCODEC" ]; then
		: # no video is ok
	else
	  case $VCODEC in
	    divx)
		OPTS="$OPTS -y xvid4"
		;;
	    theora)
		OPTS="$OPTS -vcodec libtheora -sameq"
		;;
	    *)
		die "Cannot handle VCODEC=$VCODEC"
		;;
	  esac
	fi
	case $ACODEC in
	    mp3)
		OPTS="$OPTS  -acodec libmp3lame"
		# implied by xvid
		;;
	    vorbis)
#		OPTS="$OPTS -af resample=16000" # for a720 input
		OPTS="$OPTS -acodec vorbis -ac 2"
		;;
	    wmav2)
		OPTS="$OPTS -acodec wmav2"
		;;
	    *)
		die Cannot handle ACODEC=$ACODEC
		;;
	esac
	;;
esac
if [ -n "$WIDTH" ]; then
#    OPTS="$OPTS -vf scale=$WIDTH:$HEIGHT"
:
fi
if [ -n "$LAVCOPTS" ]; then
    # remove superfluous leading ":"
    OPTS="$OPTS -lavcopts ${LAVCOPTS:1}"
fi

ffmpeg -y -i "$IFILE" $OPTS "$OFILE"
