#!/bin/bash -x
PROFILE=$1
IFILE=$2
OFILE=$3
LIBDIR=/home/martin/video
. $LIBDIR/$PROFILE

die() {
    echo >&2 "$@"
    exit 1
}

case $VCODEC-$ACODEC in
    s263-samr)
#	OPTS="$OPTS -of lavf -lavfopts format=mov"
	OPTS="$OPTS -oac lavc -ovc lavc -af resample=8000 -srate 8000 -lavcopts
vcodec=h263:acodec=libamr_nb:abitrate=8 "
	;;
    *)
	# special cases out of the way, now handle a-v separately
	case $VCODEC in
	    divx)
		OPTS="$OPTS -y xvid4"
		;;
	    theora)
		die "Cannot handle Theora in Transcode"
		;;
	    *)
		die "Cannot handle VCODEC=$VCODEC"
		;;
	esac
	case $ACODEC in
	    mp3)
		OPTS="$OPTS  -E 16000" # for a720 input
		# implied by xvid
		# OPTS="$OPTS -oac mp3lame"  # -lameopts preset=standard"
		;;
	    vorbis)
#		OPTS="$OPTS -af resample=16000" # for a720 input
		OPTS="$OPTS -oac lavc"
		LAVCOPTS="$LAVCOPTS:acodec=vorbis"
		;;
	    *)
		die Cannot handle ACODEC=$ACODEC
		;;
	esac
	;;
esac
if [ -n "$WIDTH" ]; then
    OPTS="$OPTS -vf scale=$WIDTH:$HEIGHT"
fi
if [ -n "$LAVCOPTS" ]; then
    # remove superfluous leading ":"
    OPTS="$OPTS -lavcopts ${LAVCOPTS:1}"
fi

transcode -i "$IFILE" -o "$OFILE" $OPTS
